### ISSUE TITLE
image rebuild

### ISSUE THREAD

**Issue by natm** [slother/docker-ooklaserver#1]
Hello,

Please could you rebuild the `slother/docker-ooklaserver` image on Docker hub? (to include the latest ookla server version).

Container is working great, but I get a warning due to the server being slightly old.

Thanks!

Nat.

**Comment by slother** [comment]
Sorry about that :) I rebuilded the image. Actually server should update automatically, but it doesnt - ill try to fix it later.

**Comment by natm** [comment]
excellent, thanks!

**Comment by natm** [comment]
```
port: 8080
 netgauge
  details: Version: 2.5 Build Date: 2017-08-15.1314.4ae12d5
  status: PASSED
 websocket
  details: Version: 2.5 Build Date: 2017-08-15.1314.4ae12d5
  status: PASSED
```

Confirmed as working
